config/routes.rb
Rails.application.routes.draw do

  resources :wets
  resources :problems
  resources :masses
  resources :photos
  resources :molts
  resources :feeds
  resources :pets
  resources :posts
  devise_for :users
root 'pages#landing'
get 'pages/about'
  get '/pets/:id/feed' => 'feeds#new', as: "pets_feeding"
  get '/pets/:id/molt' => 'molts#new', as: "pets_molting"
  get '/pets/:id/photo' => 'photos#new', as: "pets_photing"
  get '/pets/:id/photos' => 'photos#pet_photos', as: "pet_photos"
  get '/pets/:id/mass' => 'masses#new', as: "pets_massing"
  get '/pets/:id/masses' => 'masses#pet_masses', as: "pet_masses"
  get '/pets/:id/problem' => 'problems#new', as: "pets_probleming"
  get '/pets/:id/problems' => 'problems#pet_problems', as: "pet_problems"
  get '/pets/:id/wet' => 'wets#new', as: "pets_weting"
  get '/pets/:id/wets' => 'wets#pet_wets', as: "pet_wets"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feed.rb
class Feed < ApplicationRecord
  validates :date, presence: true
  belongs_to :pet
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action  :authenticate_user!
  before_action :owner, except: [:create, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show

  end

  # GET /feeds/new
  def new
    @feed = Feed.new

  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        feeding
        format.html { redirect_to pet_path(@feed.pet_id), notice: 'Информация о кормлении успешно сохранена.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { redirect_to pets_feeding_path(@feed.pet_id), notice: 'Информация о кормлении не сохранена. Укажтите дату.'}
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        feeding
        format.html { redirect_to @feed, notice: 'Информация успешно обновлена.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    feeding
    respond_to do |format|
      format.html { redirect_to pet_path(@feed.pet_id), notice: 'Информация о кормлении успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    def feeding
      @pet = Pet.find(@feed.pet_id)
      if @pet.feeds.order(:date).last.nil?
        @pet.lastfeed = nil
        @pet.nextfeed = nil
        else
            @pet.lastfeed = @pet.feeds.order(:date).last.date
            @pet.nextfeed=@pet.lastfeed+@pet.feedtimes
      end


      @pet.save

    end
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end
  def owner
    @pet = current_user.pets.find_by(id: params[:id])
    redirect_to pets_path if @pet.nil?
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:desk, :date, :pet_id)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<div class="form-control">
<%= form_for(feed) do |f| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <% if @pet.feeds.last.nil?
   @feeddesk=""
   else
   @feeddesk=@pet.feeds.last.desk
   end%>
    <%= f.label :desk, "Описание", class:"col-form-label" %>
    <%= f.text_area :desk, class:"form-control", value: @feeddesk  %>
    <%= f.label :date, "Дата кормления", class:"col-form-label" %>
    <%= f.date_field :date, class:"form-control", value: Date.today %>
<br>
    <%= f.hidden_field :pet_id, :value => params.require(:id).to_i %>


    <%= f.submit :Записать , class: "btn btn-success" %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Desk</th>
      <th>Date</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.desk %></td>
        <td><%= feed.date %></td>
        <td><%= feed.pet_id %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>Укажите параметры кормления</h1>

<%= render 'form', feed: @feed %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desk:</strong>
  <%= @feed.desk %>
</p>

<p>
  <strong>Date:</strong>
  <%= @feed.date %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @feed.pet_id %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>