config/routes.rb
Rails.application.routes.draw do

  resources :wets
  resources :problems
  resources :masses
  resources :photos
  resources :molts
  resources :feeds
  resources :pets
  resources :posts
  devise_for :users
root 'pages#landing'
get 'pages/about'
  get '/pets/:id/feed' => 'feeds#new', as: "pets_feeding"
  get '/pets/:id/molt' => 'molts#new', as: "pets_molting"
  get '/pets/:id/photo' => 'photos#new', as: "pets_photing"
  get '/pets/:id/photos' => 'photos#pet_photos', as: "pet_photos"
  get '/pets/:id/mass' => 'masses#new', as: "pets_massing"
  get '/pets/:id/masses' => 'masses#pet_masses', as: "pet_masses"
  get '/pets/:id/problem' => 'problems#new', as: "pets_probleming"
  get '/pets/:id/problems' => 'problems#pet_problems', as: "pet_problems"
  get '/pets/:id/wet' => 'wets#new', as: "pets_weting"
  get '/pets/:id/wets' => 'wets#pet_wets', as: "pet_wets"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :feeds, dependent: :destroy
  has_many :molts, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :mass, dependent: :destroy
  has_many :problems, dependent: :destroy
  has_many :wets, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
before_action  :authenticate_user!, except: [:show]
  before_action :owner, except: [:index, :new, :create, :show]
  before_action :pet_private, only: [:show]
  helper_method :sort_column, :sort_direction
  # GET /pets
  # GET /pets.json
  def index
    @pets = current_user.pets.order(sort_column + " " + sort_direction)
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = current_user.pets.build
    @pet.feedtimes = 1
    @pet.bday = Date.today
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = current_user.pets.build(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pets_path, notice: 'Информация о питомце успешно сохранена.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Информация о питомце успешно обновлена.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Информация о питомце успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    current_user.pets.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  def owner
    @pet = current_user.pets.find_by(id: params[:id])
    if @pet.nil?
    redirect_to pets_path
    end


  end
  def pet_private
    if !Pet.find_by(id: params[:id]).private or (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?)
      elsif
      redirect_to pets_path
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :species, :sex, :desk, :bday, :feedtimes, :wettime, :private )
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<div class="form-control">
  <%= form_for(pet) do |f| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
     <li style="color: #B00100">Поле "Имя питомца" не может быть пустым</li>

    </div>
  <% end %>

      <%= f.label :name, "Идентификатор питомца", class:"col-form-label" %>
      <%= f.text_field :name, class:"form-control" %>
      <%= f.label :species, "Вид", class:"col-form-label" %>
      <%= f.text_field :species, class:"form-control" %>
      <%= f.label :sex, "Пол питомца", class:"col-form-label" %>
<br>

      <%= f.radio_button :sex, "Самка" %>
      <%= f.label :sex, "Самка", class:"col-form-label" %>
      <%= f.radio_button :sex, "Самец" %>
      <%= f.label :sex, "Самец", class:"col-form-label" %>
      <br>
      <%= f.label :desk, "Описание", class:"col-form-label" %>
    <%= f.text_area :desk, class:"form-control" %>
    <%= f.label :bday, "День рождения питомца", class:"col-form-label" %>
    <%= f.date_field :bday, class:"form-control" %>
    <%= f.label :feedtimes, "Интервал кормления в днях", class:"col-form-label" %>
    <%= f.number_field(:feedtimes, in: 1..365, step: 1, class:"form-control") %>
      <%= f.label :wettime, "Интервал увлажнения в днях", class:"col-form-label" %>
      <%= f.number_field(:wettime, in: 1..365, step: 1, class:"form-control") %>

      <%= f.check_box :private %>
      <%= f.label :private, "Не показывать информацию об этом питомце никому кроме меня", class:"col-form-label" %>

    <br>
    <%= f.submit :Записать , class: "btn btn-success" %>
<% end %>
</div>

app/views/pets/_postform.html.erb
<div>
  <%= form_for(post) do |f| %>
      <% if post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this feed from being saved:</h2>

            <ul>
              <% post.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


      <%= f.text_area :content, class:"form-control"  %>


      <%= f.hidden_field :pet_id, :value => params.require(:id).to_i %>


      <%= f.submit :Добавить_запись , class: "btn btn-success avatar" %>
      </div>
  <% end %>

app/views/pets/edit.html.erb
<h1>Измерение информации о питомце</h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>Ваши животные</h1>

<table class="table table-inverse">
  <thead>
    <tr>
      <th>#</th>

      <th><%= sortable "name", "Идентификатор"%></th>
      <th><%= sortable "species", "Вид"%></th>
      <th><%= sortable "sex", "Пол" %></th>
      <th><%= sortable "bday", "Дата рождения" %></th>
      <th><%= sortable "lastfeed", "Последнее кормление"%></th>
      <th><%= sortable "nextfeed", "Следующее кормление"%></th>
      <th><%= sortable "nextfeed", "Следующее увлажнение"%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody><% i=0%>
    <% @pets.each do |pet| %>
      <td><%= i+=1 %></td>

      <td class="pet-name"><%= link_to pet.name, pet %></td>
      <td><%= pet.species %></td>
      <td><%= pet.sex %></td>

      <td><%= pet.bday %></td>
      <td><%= pet.lastfeed%></td>
      <td> <%pet.nextfeed = Date.today if pet.nextfeed.nil?%>
        <% if pet.nextfeed <= Date.today%>
            <span style="background-color: #b00100"> <%= pet.nextfeed%></span>
        <%else%>
            <%= pet.nextfeed%>
        <% end%>

      </td>
      <td> <%pet.nextwet = Date.today if pet.nextwet.nil?%>
        <% if pet.nextwet <= Date.today%>
            <span style="background-color: #b00100"> <%= pet.nextwet%></span>
        <%else%>
            <%= pet.nextwet%>
        <% end%>

      </td>

      <td>
      <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">

        <%= link_to 'Удалить', pet, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "btn btn-danger" %>
      </div>
      </td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>
<%  if user_signed_in? %>
<%= link_to 'Добавить питомца', new_pet_path, class: "btn btn-success btn-block" %>
<% end %>

app/views/pets/new.html.erb
<h1>Новый питомец</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<div class="container">
  <div class="row ">
<div class="card-block col-sm-3">
  <% unless @pet.photos.last.nil? %>
      <img src="<%= @pet.photos.last.image.url(:thumb)%>" class="avatar img-thumbnail">
  <% end%>
  <ul class="list-group">
    <%= link_to 'Все фото этого питомца', pet_photos_path(@pet.id), class: "list-group-item list-group-item-success" %>
    <%= link_to 'График веса', pet_masses_path, class: "list-group-item list-group-item-success" %>

    <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>
        <%= link_to 'Добавить фото', pets_photing_path(@pet), class: "list-group-item list-group-item-success"  %>
        <%= link_to 'Редактировать анкету питомца', edit_pet_path(@pet), class: "list-group-item list-group-item-success" %>

        <%= link_to 'Удалить всю информацию о питомце', @pet, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "list-group-item list-group-item-danger" %>

    <% end %>


  </ul>
</div>
    <div class="col-sm-9 ">

    <div class="col-sm-5">
          <strong>Владелец:</strong> <%= @pet.user.nikname %><br>
      <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

    <strong>Идентификатор питомца:</strong> <%= @pet.name %><br>
      <% end %>

    <strong>Пол:</strong><%= @pet.sex %><br>
    <strong>Вид: </strong><%= @pet.species %><br>
    <strong>Дата рождения питомца:</strong> <%= @pet.bday %><br>
    <strong>Интервал кормления:</strong> <%= @pet.feedtimes %> (в днях)<br>
    <strong>Описание:</strong>   <%= @pet.desk %>
  </div>
      <div class="col-sm-7">
        <div class="card card-inverse" style="background-color: #333; border-color: #333;">
          <a data-toggle="collapse" data-parent="#accordion" href="#lastfeed" aria-expanded="true" aria-controls="collapseOne">
        <center>Последнее кормление <%= @pet.lastfeed%>. (нажмите, что бы посмотреть историю кормлений)
        </center>
      </a>
      <div id="lastfeed" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
        <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

        <%= link_to 'Покормить', pets_feeding_path(@pet), class: "btn btn-success btn-sm" %>
        <% end %>
        <table class="table table-inverse">
          <thead>
          <tr>
            <th>Дата кормления</th>
            <th>Дополнительная информация</th>
            <th><% render 'feeds/form', feed: Feed.new %>
            </th>

          </tr>
          </thead>
          <tbody>
          <% @pet.feeds.order(:date).reverse_order.each do |feed| %>
              <td><%= feed.date %></td>
              <td><%= feed.desk %></td>
              <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

                  <td><%= link_to 'Удалить', feed, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "btn btn-danger btn-sm" %></td>
              <% end %>

              </tr>
          <% end %>
          </tbody>
        </table>


      </div>
      </div>
    <div class="card card-inverse" style="background-color: #333; border-color: #333;">
      <a data-toggle="collapse" data-parent="#accordion" href="#lastwet" aria-expanded="true" aria-controls="collapseOne">
        <center>Последнее увлажнение <% if @pet.wets.last.nil? %>
              не известно
          <% else%>
              <%= @pet.wets.order(:date).last.date%>
          <%end%>.
          (нажмите, чтобы посмотреть историю увлажнений)
        </center>
      </a>
      <div id="lastwet" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
        <% link_to 'Увлажнить', pets_weting_path(@pet), class: "btn btn-success btn-sm" %>
        <table class="table table-inverse">
          <thead>
          <tr>
            <th>Дата увлажнения</th>
            <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

                <th><%= render 'wets/form', wet: Wet.new %>
            <% end %>


          </tr>
          </thead>
          <tbody>
          <% @pet.wets.order(:date).reverse_order.each do |wet| %>
              <td><%= wet.date %></td>

              <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

                  <td><%= link_to 'Удалить', wet, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "btn btn-danger btn-sm" %></td>
              <% end %>
              </tr>
          <% end %>
          </tbody>
        </table>


      </div>
    </div>
        <div class="card card-inverse" style="background-color: #333; border-color: #333;">
          <a data-toggle="collapse" data-parent="#accordion" href="#molting" aria-expanded="true" aria-controls="collapseOne">
            <center>
              Последняя линька
              <% if @pet.molts.last.nil? %>
                    не известна
                        <% else%>
               <%= @pet.molts.order(:date).last.date%>
              <%end%>. (нажмите, чтобы посмотреть историю линек)</center>
          </a>
          <div id="molting" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
            <% link_to 'Добавить линьку', pets_molting_path(@pet), class: "btn btn-success btn-sm"  %>
            <table class="table table-inverse">
              <thead>
              <tr>
                <th>Дата линьки</th>
                <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

                    <th><%= render 'molts/form', molt: Molt.new %>
                <% end %>
            </th>
              </tr>
              </thead>
              <tbody>
              <% @pet.molts.order(:date).reverse_order.each do |feed| %>
                  <td><%= feed.date %></td>

                  <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

                      <td><%= link_to 'Удалить', feed, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "btn btn-danger btn-sm" %></td>
                  <% end %>
                  </tr>
              <% end %>
              </tbody>
            </table>


          </div>
        </div>

    <div class="card card-inverse" style="background-color: #333; border-color: #333;">
      <a data-toggle="collapse" data-parent="#accordion" href="#problems" aria-expanded="true" aria-controls="collapseOne">
        <center>

          Последняя проблема
          <% if @pet.problems.last.nil? %>
              не известна
          <% else%>
              <%= @pet.problems.order(:date).last.date%>
          <%end%>. (нажмите, чтобы посмотреть все проблемы)</center>
      </a>
      <div id="problems" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
        <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

            <%= link_to 'Записать проблему', pets_probleming_path(@pet), class: "btn btn-success btn-sm"  %>
        <% end %>
        <table class="table table-inverse">
          <thead>
          <tr>
            <th>Дата</th>
            <th>Описание</th>
          </tr>
          </thead>
          <tbody>
          <% @pet.problems.order(:date).reverse_order.each do |problem| %>
              <td><%= problem.date %></td>
              <td><%= problem.desk %></td>
              <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>

                  <td><%= link_to 'Удалить', problem, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "btn btn-danger btn-sm" %></td>
              <% end %>

              </tr>
          <% end %>
          </tbody>
        </table>



      </div>
    </div>
  </div>
<div class="col-sm-12">
    <% if (user_signed_in? and !current_user.pets.find_by(id: params[:id]).nil?) %>
    <%= render 'postform', post: Post.new %>
    <% end %>
        <br>

    <% @pet.posts.order(:updated_at).reverse_order.each do |post| %>
        <div class="card">
          <div class="card-block">
            <h6 class="card-subtitle mb-2 text-muted">
        <%= post.updated_at.to_s(:ru_datetime)%><br>
            </h6>
<div class="card-text ">
        <%= post.content%>
</div>
            <% if User.find(Pet.find(post.pet_id).user_id) == current_user %>
        <%= link_to 'Удалить', post, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "btn btn-danger btn-sm " %>
            <%end %>
                </div></div>

    <% end %>
</div>
  </div></div></div>