config/routes.rb
Rails.application.routes.draw do

  resources :wets
  resources :problems
  resources :masses
  resources :photos
  resources :molts
  resources :feeds
  resources :pets
  resources :posts
  devise_for :users
root 'pages#landing'
get 'pages/about'
  get '/pets/:id/feed' => 'feeds#new', as: "pets_feeding"
  get '/pets/:id/molt' => 'molts#new', as: "pets_molting"
  get '/pets/:id/photo' => 'photos#new', as: "pets_photing"
  get '/pets/:id/photos' => 'photos#pet_photos', as: "pet_photos"
  get '/pets/:id/mass' => 'masses#new', as: "pets_massing"
  get '/pets/:id/masses' => 'masses#pet_masses', as: "pet_masses"
  get '/pets/:id/problem' => 'problems#new', as: "pets_probleming"
  get '/pets/:id/problems' => 'problems#pet_problems', as: "pet_problems"
  get '/pets/:id/wet' => 'wets#new', as: "pets_weting"
  get '/pets/:id/wets' => 'wets#pet_wets', as: "pet_wets"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_attached_file :image, styles: {large:"900x900>", medium: "360x240#", thumb: "240x180#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :pet
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :owner, except: [:create, :destroy, :index, :show, :pet_photos]
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def pet_photos
    @photos = Pet.find(params.require(:id).to_i).photos.paginate(:page => params[:page], :per_page => 30)
    render :index
  end

  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end
  def owner
    @pet = current_user.pets.find_by(id: params[:id])
    redirect_to pets_path if @pet.nil?
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:pet_id, :desk, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<div class="form-control">
  <%= form_for photo, html: { multipart: true }  do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :image, "Изображение" %>
    <%= f.file_field :image, class:"form-control"%>
    <%= f.label :desk, "Описание" %>
    <%= f.text_area :desk, class:"form-control" %>
    <%= f.hidden_field :pet_id, :value =>  params.require(:id).to_i %><br>
    <%= f.submit :загрузить, class: "btn btn-success" %>
<% end %>
</div>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
 <% @photos.each do |photo| %>

     <div class="card photocard ">
     <div class="card-block">
       <a href="<%= photo_url(photo) %>">
        <%= image_tag photo.image.url(:medium), class: "card-img img-thumbnail avatar", alt: Pet.find(photo.pet_id).sex.to_s+' '+Pet.find(photo.pet_id).species,
                      title: Pet.find(photo.pet_id).sex.to_s+' '+Pet.find(photo.pet_id).species.to_s+' '+photo.desk.to_s  %><br>
       </a>

         <strong>
       <%= Pet.find(photo.pet_id).sex %>
       <%= Pet.find(photo.pet_id).species %></strong><br>
        <%= photo.desk%> <br>
       <ul class="list-group">
        <%= link_to 'Все фото с этим питомцем', pet_photos_path(photo.pet_id), class: "list-group-item list-group-item-success" %>

             <%= link_to 'Перейти на страницу питомца', pet_path(photo.pet_id), class: "list-group-item list-group-item-success" %>
         <% if User.find(Pet.find(photo.pet_id).user_id) == current_user %>
           <%= link_to 'Удалить', photo, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "list-group-item list-group-item-danger" %>
         <% end %></ul>
     </div>
     </div>
    <% end %>

 <%= will_paginate @photos %>


<br>

app/views/photos/new.html.erb
<h1>Загрузить фото</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<center>

    <p>
      <%= image_tag @photo.image.url(:large), alt: @photo.pet.sex.to_s+' '+@photo.pet.species,
          title: @photo.pet.sex.to_s+' '+@photo.pet.species.to_s+' '+@photo.desk.to_s %><br>

      <strong>
        <%= @photo.pet.sex %>
        <%= @photo.pet.species %></strong><br>
      <%= @photo.desk %>
    </p>
  <% if User.find(@photo.pet.user_id) == current_user %>
      <%= link_to 'Удалить', @photo, method: :delete, data: { confirm: 'Вы уверенны?' }, class: "btn btn-danger btn-sm" %>
  <% end %>

  <%= link_to 'Все фотографии', photos_path , class: "btn btn-success btn-sm" %>
  <br><br>
</center>