config/routes.rb
Rails.application.routes.draw do

  resources :wets
  resources :problems
  resources :masses
  resources :photos
  resources :molts
  resources :feeds
  resources :pets
  resources :posts
  devise_for :users
root 'pages#landing'
get 'pages/about'
  get '/pets/:id/feed' => 'feeds#new', as: "pets_feeding"
  get '/pets/:id/molt' => 'molts#new', as: "pets_molting"
  get '/pets/:id/photo' => 'photos#new', as: "pets_photing"
  get '/pets/:id/photos' => 'photos#pet_photos', as: "pet_photos"
  get '/pets/:id/mass' => 'masses#new', as: "pets_massing"
  get '/pets/:id/masses' => 'masses#pet_masses', as: "pet_masses"
  get '/pets/:id/problem' => 'problems#new', as: "pets_probleming"
  get '/pets/:id/problems' => 'problems#pet_problems', as: "pet_problems"
  get '/pets/:id/wet' => 'wets#new', as: "pets_weting"
  get '/pets/:id/wets' => 'wets#pet_wets', as: "pet_wets"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wet.rb
class Wet < ApplicationRecord
  validates :date, presence: true
  belongs_to :pet
end

app/controllers/wets_controller.rb
class WetsController < ApplicationController
  before_action :set_wet, only: [:show, :edit, :update, :destroy]
  before_action  :authenticate_user!
  before_action :owner, except: [:create, :destroy]

  # GET /wets
  # GET /wets.json
  def index
    @wets = Wet.all
  end
  def pet_wets
    @wets = Pet.find(params.require(:id).to_i).wets
    render :index
  end
  # GET /wets/1
  # GET /wets/1.json
  def show
  end

  # GET /wets/new
  def new
    @wet = Wet.new
  end

  # GET /wets/1/edit
  def edit
  end

  # POST /wets
  # POST /wets.json
  def create
    @wet = Wet.new(wet_params)

    respond_to do |format|
      if @wet.save
        nextwetset
        format.html { redirect_to pet_path(@wet.pet_id), notice: 'Данные об увлажнении успешно сохранены.' }
        format.json { render :show, status: :created, location: @wet }
      else
        format.html { render :new }
        format.json { render json: @wet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wets/1
  # PATCH/PUT /wets/1.json
  def update
    respond_to do |format|
      if @wet.update(wet_params)
        format.html { redirect_to pet_path(@wet.pet_id), notice: 'Данные об увлажнении успешно сохранены.' }
        format.json { render :show, status: :ok, location: @wet }
      else
        format.html { render :edit }
        format.json { render json: @wet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wets/1
  # DELETE /wets/1.json
  def destroy
    @wet.destroy
    nextwetset
    respond_to do |format|
      format.html { redirect_to pet_path(@wet.pet_id), notice: 'Данные об увлажнении успешно удалены.' }
      format.json { head :no_content }
    end
  end

  private
  def nextwetset
    @pet=Pet.find(@wet.pet_id)
    if @pet.wets.last.nil?
      @pet.nextwet = Date.today
    elsif
    @pet.nextwet=@pet.wets.order(:date).last.date+@pet.wettime.to_i
    end
    @pet.save
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_wet
      @wet = Wet.find(params[:id])
    end
  def owner
    @pet = current_user.pets.find_by(id: params[:id])
    redirect_to pets_path if @pet.nil?
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wet_params
      params.require(:wet).permit(:pet_id, :date)
    end
end

app/helpers/wets_helper.rb
module WetsHelper
end

app/views/wets/_form.html.erb
<%= form_for(wet) do |f| %>
  <% if wet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wet.errors.count, "error") %> prohibited this wet from being saved:</h2>

      <ul>
      <% wet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.date_field :date, class:"form-control", value: Date.today %>
    <%= f.hidden_field :pet_id, :value =>  params.require(:id).to_i %>
    <br>
    <%= f.submit  :Записать , class: "btn btn-success"%>

<% end %>

app/views/wets/edit.html.erb
<h1>Editing Wet</h1>

<%= render 'form', wet: @wet %>

<%= link_to 'Show', @wet %> |
<%= link_to 'Back', wets_path %>

app/views/wets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wets</h1>

<table>
  <thead>
    <tr>
      <th>Pet</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wets.each do |wet| %>
      <tr>
        <td><%= wet.pet_id %></td>
        <td><%= wet.date %></td>
        <td><%= link_to 'Show', wet %></td>
        <td><%= link_to 'Edit', edit_wet_path(wet) %></td>
        <td><%= link_to 'Destroy', wet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wet', new_wet_path %>

app/views/wets/new.html.erb
<%= render 'form', wet: @wet %>

<%= link_to 'Back', wets_path %>

app/views/wets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @wet.pet_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @wet.date %>
</p>

<%= link_to 'Edit', edit_wet_path(@wet) %> |
<%= link_to 'Back', wets_path %>